name: auto-code-rover
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - ld_impl_linux-64
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.2.0
  - pip=23.3.1
  - python=3.11.7
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - loguru=0.7.2
  - rich=13.7.1
  - pip:
      - annotated-types==0.6.0
      - anyio==4.2.0
      - beautifulsoup4==4.12.3
      - boto3==1.34.122
      - certifi==2023.11.17
      - distro==1.9.0
      - docstring-parser==0.15
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.27.0
      - idna==3.6
      - lxml==5.1.0
      - openai==1.23.3
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - python-dotenv==1.0.0
      - rich==13.7.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - tenacity==8.2.3
      - termcolor==2.4.0
      - timeout-decorator==0.5.0
      - tqdm==4.66.1
      - typing-extensions==4.9.0
      - unittest-xml-reporting==3.2.0
      - coverage==7.4.4
      - pylint==3.1.0
      - litellm==1.41.24
      - ollama==0.1.8
      - flask==3.0.3
      - flask_cors==4.0.0
      - unidiff==0.7.5
