name: auto-code-rover
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_3
  - libgomp=13.2.0=h807b86a_3
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.2.0=hd590300_1
  - pip=23.3.1=py311h06a4308_0
  - python=3.11.7=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023d=h04d1e81_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - unidiff
  - requests
  - pip:
      - annotated-types==0.6.0
      - anyio==4.2.0
      - beautifulsoup4==4.12.3
      - certifi==2023.11.17
      - distro==1.9.0
      - docstring-parser==0.15
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - idna==3.6
      - lxml==5.1.0
      - openai==1.8.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - python-dotenv==1.0.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - tenacity==8.2.3
      - termcolor==2.4.0
      - tqdm==4.66.1
      - typing-extensions==4.9.0
      - unittest-xml-reporting==3.2.0
      - coverage
      - pylint
